#!/bin/bash
Bootstrap: docker
From: ubuntu:22.04

%files
   ../SSAxgeo/ /opt/

%post
apt-get update -qq -y

apt install -y libcifpp-dev dssp dub curl

apt install -y rsync wget python3 python3-pip git nano cmake gdc

mkdir /app/
cd /app/

# install dependencies
pip3 install jupyterlab
pip3 install localpdb pandas nglview seaborn scipy scikit-learn hdbscan  numpy matplotlib
pip3 install melodia_py

#install SSAxgeo
mv /opt/SSAxgeo /app/
cd /app/SSAxgeo/
pip3 install -e ./

# compile diff
cd /app/SSAxgeo/diffgeo/
dub build --build=release --compiler=gdc --force

%runscript
exec /bin/bash "$@"

%startscript
exec /bin/bash "$@"

%test
    mkdssp -h
    python3 -c "import melodia_py"
    ssaxgeo -h
    mkdssp -h
    dssp -h
    localpdb_setup -h